steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/react-gcp-420504/react-gcp', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/react-gcp-420504/react-gcp']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'react-gcp', '--image', 'gcr.io/react-gcp-420504/react-gcp', '--region', 'us-central1', '--platform', 'managed','--port','3000']
images:
- gcr.io/react-gcp-420504/react-gcp